/*------------------------------------------------------------------------------------------------*
 * Copyright (C) by the DBCSR developers group - All rights reserved                              *
 * This file is part of the DBCSR library.                                                        *
 *                                                                                                *
 * For information on the license, see the LICENSE file.                                          *
 * For further information please visit https://dbcsr.cp2k.org                                    *
 * SPDX-License-Identifier: GPL-2.0+                                                              *
 *------------------------------------------------------------------------------------------------*/
#if defined(__OPENCL)
#include "opencl_libsmm.h"
/* Header opencl_kernels.h is generated by the build system using acc_opencl.sh */
#include "opencl_kernels.h"
#include <assert.h>

#if !defined(OPENCL_SOURCE_LOAD) && 0
# define OPENCL_SOURCE_LOAD
#endif


#if defined(__cplusplus)
extern "C" {
#endif

int libsmm_acc_init(void)
{
#if !defined(__DBCSR_ACC)
  /* DBCSR may call acc_init() as well as libsmm_acc_init() since both interface are used.
   * libsmm_acc_init may privately call acc_init (as it depends on the ACC interface).
   * The implementation of acc_init() should be safe against "over initialization".
   * However, DBCSR only calls acc_init() and expects an implicit libsmm_acc_init().
   */
  ACC_OPENCL_RETURN(acc_init());
#else
  /* avoid recursion */
  return EXIT_SUCCESS;
#endif
}


int libsmm_acc_finalize(void)
{
  /* acc_finalize() is not called since it can be used independently  */
  return EXIT_SUCCESS;
}


acc_bool_t libsmm_acc_is_thread_safe(void)
{
  return 1/*true*/;
}


int libsmm_acc_transpose(const int* dev_trs_stack, int offset, int stack_size,
  void* dev_data, libsmm_acc_data_t datatype, int m, int n, int max_kernel_dim, void* stream)
{
  int result = EXIT_SUCCESS;
  ACC_OPENCL_UNUSED(max_kernel_dim); /* TODO */
  assert((NULL != dev_trs_stack && NULL != dev_data && 0 <= stack_size) || 0 == stack_size);
  if (0 < stack_size && 1 < (m * n)) {
    typedef struct config_t {
      cl_kernel kernel;
      size_t wgsize;
    } config_t;
    struct { int m, n; } key;
    config_t *config;
    /* homogeneous key-data (no need for prior memset) */
    key.m = m; key.n = n; /* initialize key */
    config = (config_t*)libxsmm_xdispatch(&key, sizeof(key));
    if (NULL == config) {
      char build_options[ACC_OPENCL_BUFFER_MAXSIZE], fname[32];
      const char *const env_options = getenv("ACC_OPENCL_TRANS_BUILD_OPTIONS");
      int nchar = ACC_OPENCL_SNPRINTF(fname, sizeof(fname), "xtrans%ix%i", m, n);
      const char* typename = "";
      switch (datatype) {
        case dbcsr_type_real_8: {
          typename = "char8"; /* double */
          fname[0] = 'd';
        } break;
        case dbcsr_type_real_4: {
          typename = "float";
          fname[0] = 's';
        } break;
        default: ;
      }
      nchar = ((0 < nchar && (int)sizeof(fname) > nchar)
        ? ACC_OPENCL_SNPRINTF(build_options, sizeof(build_options), "%s -DT=%s -DFN=%s -DSM=%i -DSN=%i",
        (NULL == env_options || '\0' == *env_options) ? "" : env_options, typename, fname, m, n) : 0);
      if ('\0' != *typename && 0 < nchar && (int)sizeof(build_options) > nchar) {
        cl_device_id active_device;
        const char *const env_inplace = getenv("ACC_OPENCL_TRANS_INPLACE");
        const int inplace = (m == n &&
          ((NULL != env_inplace && '\0' != *env_inplace && '0' != *env_inplace)
            ||  (EXIT_SUCCESS == acc_opencl_device(stream, &active_device)
              && EXIT_SUCCESS == acc_opencl_device_vendor(active_device, "intel"))));
        config_t new_config;
        FILE* file = NULL;
#if defined(OPENCL_SOURCE_LOAD)
        const char *const paths[] = {
          "../../exts/dbcsr/src/acc/opencl/smm/kernel",
          "opencl/smm/kernels"
        };
        file = acc_opencl_source_open(
          inplace ? "transpose_inplace.cl" : "transpose.cl",
          paths, sizeof(paths) / sizeof(*paths));
        if (NULL != file) {
          char* lines[128];
          const int nlines = acc_opencl_source(file, lines,
            NULL/*extensions*/, sizeof(lines) / sizeof(*lines),
            /* whether to cleanup the loaded source code or not */
# if defined(NDEBUG)
            1);
# else
            0);
# endif
          fclose(file);
          result = acc_opencl_kernel((const char**)lines, nlines, build_options, fname, &new_config.kernel);
          if (0 < nlines) free(lines[0]);
        }
#endif
#if defined(OPENCL_SOURCE_TRANSPOSE) && defined(OPENCL_SOURCE_TRANSPOSE_INPLACE)
        if (EXIT_SUCCESS == result && NULL == file) {
          const char *const transpose_inp[] = { OPENCL_SOURCE_TRANSPOSE_INPLACE };
          const char *const transpose_oop[] = { OPENCL_SOURCE_TRANSPOSE };
          result = acc_opencl_kernel(inplace ? transpose_inp : transpose_oop, 1/*nlines*/,
            build_options, fname, &new_config.kernel);
        }
#endif
        if (EXIT_SUCCESS == result) {
          int max_wgsize;
          result = acc_opencl_wgsize(new_config.kernel, NULL/*preferred_multiple*/, &max_wgsize);
          if (EXIT_SUCCESS == result) {
            const char *const env_wgsize = getenv("ACC_OPENCL_TRANS_WGSIZE");
            assert(0 < max_wgsize);
            if (NULL == env_wgsize || '\0' == *env_wgsize) {
              new_config.wgsize = (size_t)m;
            }
            else {
              const int int_wgsize = atoi(env_wgsize);
              new_config.wgsize = (size_t)((m <= int_wgsize || 0 == (m % int_wgsize)) ? int_wgsize : m);
            }
            if (max_wgsize < (int)new_config.wgsize) new_config.wgsize = 1;
            config = (config_t*)libxsmm_xregister(&key, sizeof(key), sizeof(new_config), &new_config);
          }
        }
      }
      else {
        result = EXIT_FAILURE;
      }
    }
    assert((NULL != config && NULL != config->kernel && 0 < config->wgsize) || EXIT_SUCCESS != result);
    if (EXIT_SUCCESS == result) {
      const size_t work_size = config->wgsize * stack_size;
      ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 0, sizeof(cl_mem), ACC_OPENCL_MEM(dev_trs_stack)),
        "set batch-list argument of transpose kernel", result);
      ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 1, sizeof(int), &offset),
        "set offset argument of transpose kernel", result);
      ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 2, sizeof(cl_mem), ACC_OPENCL_MEM(dev_data)),
        "set matrix-data argument of transpose kernel", result);
      ACC_OPENCL_CHECK(clEnqueueNDRangeKernel(*ACC_OPENCL_STREAM(stream),
        config->kernel, 1/*work_dim*/, NULL, &work_size, &config->wgsize, 0, NULL, NULL),
        "launch transpose kernel", result);
    }
  }
  ACC_OPENCL_RETURN(result);
}


int libsmm_acc_process(const int* host_param_stack, const int* dev_param_stack, int stack_size,
  int nparams, libsmm_acc_data_t datatype, const void* dev_a_data, const void* dev_b_data, void* dev_c_data,
  int m_max, int n_max, int k_max, int max_kernel_dim, acc_bool_t def_mnk, void* stack_stream, void* c_stream)
{
  int result = EXIT_SUCCESS;
  ACC_OPENCL_UNUSED(host_param_stack); ACC_OPENCL_UNUSED(nparams); ACC_OPENCL_UNUSED(c_stream); /* TODO */
  assert((NULL != dev_param_stack && NULL != dev_a_data && NULL != dev_b_data && NULL != dev_c_data) || 0 == stack_size);
  assert(0 < nparams && 0 < max_kernel_dim && NULL != stack_stream);
  if (0 <= stack_size) {
    if (0 < stack_size && def_mnk/*homogeneous*/ &&
        0 < m_max && m_max <= max_kernel_dim &&
        0 < n_max && n_max <= max_kernel_dim &&
        0 < k_max && k_max <= max_kernel_dim)
    {
      typedef struct config_t {
        cl_kernel kernel;
      } config_t;
      struct { int m, n, k; } key;
      config_t *config;
      /* homogeneous key-data (no need for prior memset) */
      key.m = m_max; key.n = n_max; key.k = k_max; /* initialize key */
      config = (config_t*)libxsmm_xdispatch(&key, sizeof(key));
      if (NULL == config) {
        char build_options[ACC_OPENCL_BUFFER_MAXSIZE], fname[48];
        int nchar = ACC_OPENCL_SNPRINTF(fname, sizeof(fname), "xmm%ix%ix%i", m_max, n_max, k_max);
        const char* extensions = NULL;
        if (0 < nchar && (int)sizeof(fname) > nchar) {
          cl_device_id active_device;
          result = acc_opencl_device(stack_stream, &active_device);
          if (EXIT_SUCCESS == result) {
            const char *const env_options = getenv("ACC_OPENCL_SMM_BUILD_OPTIONS");
            const char *typename = NULL, *atomic_t = NULL, *atomic_f = NULL;
            assert(NULL != active_device);
            switch (datatype) {
              case dbcsr_type_real_8: {
                extensions = "cl_khr_fp64 cl_khr_int64_base_atomics";
                if (EXIT_SUCCESS == acc_opencl_device_ext(active_device, &extensions, 1)) {
                  typename = "double";
                  atomic_t = "long";
                  atomic_f = "atom_cmpxchg";
                  fname[0] = 'd';
                }
              } break;
              case dbcsr_type_real_4: {
                extensions = "cl_khr_global_int32_base_atomics";
                if (EXIT_SUCCESS == acc_opencl_device_ext(active_device, &extensions, 1)) {
                  typename = "float";
                  atomic_t = "int";
                  atomic_f = "atomic_cmpxchg";
                  fname[0] = 's';
                }
              } break;
              default: ;
            }
            if (NULL != typename && '\0' != *typename) {
              const char *const build_setup = "%s -cl-fast-relaxed-math"
                " -DT=%s -DTA=\"%s\" -DFA=%s -DFN=%s -DSM=%i -DSN=%i -DSK=%i";
              nchar = ACC_OPENCL_SNPRINTF(build_options, sizeof(build_options), build_setup,
                (NULL == env_options || '\0' == *env_options) ? "" : env_options,
                typename, atomic_t, atomic_f, fname, m_max, n_max, k_max);
              if (0 >= nchar || (int)sizeof(build_options) <= nchar) result = EXIT_FAILURE;
            }
            else {
              result = EXIT_FAILURE;
              ACC_OPENCL_ERROR("insufficient device capabilities", result);
            }
          }
        }
        else {
          result = EXIT_FAILURE;
        }
        if (EXIT_SUCCESS == result) {
          config_t new_config;
          FILE* file = NULL;
#if defined(OPENCL_SOURCE_LOAD)
          const char *const paths[] = {
            "../../exts/dbcsr/src/acc/opencl/smm/kernel",
            "opencl/smm/kernels"
          };
          file = acc_opencl_source_open("multiply.cl", paths, sizeof(paths) / sizeof(*paths));
          if (NULL != file) {
            char* lines[128];
            const int nlines = acc_opencl_source(file, lines,
              extensions, sizeof(lines) / sizeof(*lines),
              /* whether to cleanup the loaded source code or not */
# if defined(NDEBUG)
              1);
# else
              0);
# endif
            fclose(file);
            result = acc_opencl_kernel((const char**)lines, nlines, build_options, fname, &new_config.kernel);
            if (0 < nlines) free(lines[0]);
          }
#endif
#if defined(OPENCL_SOURCE_MULTIPLY)
          if (EXIT_SUCCESS == result && NULL == file) {
            const char *const lines[] = { OPENCL_SOURCE_MULTIPLY };
            result = acc_opencl_kernel(lines, 1/*nlines*/,
              build_options, fname, &new_config.kernel);
          }
#endif
          if (EXIT_SUCCESS == result) {
            int max_wgsize;
            result = acc_opencl_wgsize(new_config.kernel, NULL/*preferred_multiple*/, &max_wgsize);
            if (EXIT_SUCCESS == result) {
              assert(0 < max_wgsize);
              if (n_max <= max_wgsize) {
                config = (config_t*)libxsmm_xregister(&key, sizeof(key), sizeof(new_config), &new_config);
              }
              else result = EXIT_FAILURE;
            }
          }
        }
        else {
          result = EXIT_FAILURE;
        }
      }
      assert((NULL != config && NULL != config->kernel) || EXIT_SUCCESS != result);
      if (EXIT_SUCCESS == result) {
        const size_t wgsize = n_max, work_size = wgsize * stack_size;
        ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 0, sizeof(cl_mem), ACC_OPENCL_MEM(dev_param_stack)),
          "set batch-list argument of SMM-kernel", result);
        ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 1, sizeof(cl_mem), ACC_OPENCL_MEM(dev_a_data)),
          "set A-matrix argument of SMM-kernel", result);
        ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 2, sizeof(cl_mem), ACC_OPENCL_MEM(dev_b_data)),
          "set B-matrix argument of SMM-kernel", result);
        ACC_OPENCL_CHECK(clSetKernelArg(config->kernel, 3, sizeof(cl_mem), ACC_OPENCL_MEM(dev_c_data)),
          "set C-matrix argument of SMM-kernel", result);
        ACC_OPENCL_CHECK(clEnqueueNDRangeKernel(*ACC_OPENCL_STREAM(stack_stream),
          config->kernel, 1/*work_dim*/, NULL, &work_size, &wgsize, 0, NULL, NULL),
          "launch SMM-kernel", result);
      }
    }
    else if (0 != stack_size) { /* inhomogeneous or large */
      result = EXIT_FAILURE; /* TODO: signal host-fallback */
    }
  }
  else {
    result = EXIT_FAILURE;
  }
  ACC_OPENCL_RETURN(result);
}

#if defined(__cplusplus)
}
#endif

#endif /*__OPENCL*/
