FROM ubuntu:22.04

# we need at least Ubuntu 19.10 for:
#   git > 2.18
#   lcov > 1.13
#   openmpi > 2.1
# we need at least Ubuntu 20.04 for:
#   ninja >= 1.10
#   an OpenBLAS built with OpenMP-support

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex ; \
    apt-get update ; \
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        gnupg \
        software-properties-common \
        curl \
        ; \
    curl -LsS https://apt.kitware.com/keys/kitware-archive-latest.asc \
        | gpg --dearmor - \
        | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null ; \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main' ; \
    apt-get install -y \
        locales \
        gfortran \
        g++ \
        openmpi-bin \
        libopenmpi-dev \
	mpich \
	libmpich-dev \
        libopenblas-openmp-dev \
        cmake \
        ninja-build \
        lcov \
        pkg-config \
        git \
        python3-pip \
        unzip \
        rsync \
        valgrind \
        ; \
    rm -rf /var/lib/apt/lists/* ; \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# Make sure we have a proper unicode locale and language
ENV LANG en_US.utf8

RUN set -ex ; \
    pip3 install \
        pre-commit \
        ford \
        git-archive-all \
        ;

# Version pins: keep in sync with cmake/dependencies.cmake
ARG libxsmm_version=c14cbc6f8bc7964f8c5190a3a16b8cace03e5889

RUN set -ex ; \
    curl -LsS https://github.com/libxsmm/libxsmm/archive/${libxsmm_version}.tar.gz | tar -xz -C /opt ; \
    ln -s libxsmm-${libxsmm_version} /opt/libxsmm ; \
    make -j -C /opt/libxsmm WRAP=0

ENV PKG_CONFIG_PATH="/opt/libxsmm/lib:/opt/libxstream/lib/pkgconfig:/opt/libxs/lib/pkgconfig:${PKG_CONFIG_PATH}"

RUN set -ex ; \
    apt-get update ; \
    apt-get install -y --no-install-recommends opencl-c-headers ocl-icd-libopencl1 ; \
    rm -rf /var/lib/apt/lists/*

ARG libxstream_version=d03b33e5dcb597ec4c80d0cd644de1cab4725da3

RUN set -ex ; \
    curl -LsS https://github.com/hfp/libxstream/archive/${libxstream_version}.tar.gz | tar -xz -C /opt ; \
    ln -s libxstream-${libxstream_version} /opt/libxstream ; \
    make -j -C /opt/libxstream

ARG libxs_version=051ad3eac78fcf8b2126843a9bfbfbe1815a92c2

RUN set -ex ; \
    curl -LsS https://github.com/hfp/libxs/archive/${libxs_version}.tar.gz | tar -xz -C /opt ; \
    ln -s libxs-${libxs_version} /opt/libxs ; \
    make -j -C /opt/libxs

# Remove LTO for MPICH (default now in Ubuntu >=22)
RUN set -ex ; \
    for ff in /usr/lib/x86_64-linux-gnu/pkgconfig/mpich.pc /usr/bin/mpicc.mpich /usr/bin/mpicxx.mpich /usr/bin/mpif77.mpich /usr/bin/mpif90.mpich /usr/bin/mpifort.mpich; do \
    	sed -i -e 's/-flto=auto//g' -e 's/-ffat-lto-objects//g' ${ff}; \
    done

# Leak suppression
COPY lsan.supp /opt
ENV LSAN_OPTIONS=suppressions=/opt/lsan.supp
